<<<<<<< HEAD
[build]
  command = "npm ci && npm run build:web"
  publish = "dist"
=======
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
>>>>>>> 007db90757448dca13d518a21889c44a2a6a6af9
